"""permite fotos nulo na sala

Revision ID: 2ec7fbbb8fb8
Revises: 0013cd21da62
Create Date: 2026-07-12 01:03:50.452756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec7fbbb8fb8'
down_revision: Union[str, Sequence[str], None] = '0013cd21da62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table("salas") as batch_op:
        batch_op.alter_column(
            "fotos",
            existing_type=sa.TEXT(),
            nullable=True
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salas', 'fotos',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
